# The purpose of this CI is to build and test Linux Cross SDKs during development.
# Only a single version of the SDK will be built for each architecture and tested.
name: Develop Swift Linux Cross SDKs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-22.04
    steps:
    - uses: swift-actions/setup-swift@v2
    - uses: actions/checkout@v4
    - name: Build SDK Generator
      shell: bash
      run: ./build-sdk-generator.sh
    - uses: ./.github/actions/build-sdk
      name: Generate SDK for 6.0.3 | jammy | linux/amd64
      with:
        swift-version: 6.0.3
        distribution: jammy
        platform: linux/amd64
        target: x86_64-unknown-linux-gnu
